CREATE VIEW  VW_TOTAL AS
SELECT I.CODIGO_DO_PRODUTO, P.NOME_DO_PRODUTO, SUM(I.QUANTIDADE) AS QUANTIDADE_TOTAL FROM ITENS_NOTAS_FISCAIS I
INNER JOIN TABELA_DE_PRODUTOS P ON I.CODIGO_DO_PRODUTO = P.CODIGO_DO_PRODUTO
GROUP BY I.CODIGO_DO_PRODUTO, P.NOME_DO_PRODUTO; 

SELECT * FROM VW_TOTAL WHERE QUANTIDADE_TOTAL > 394000
ORDER BY QUANTIDADE_TOTAL DESC;