SELECT 'O cliente ' + C.NOME + ' comprou R$ ' +
TRIM(STR(SUM(I.QUANTIDADE * I.PRECO), 10, 2)) + ' no ano de ' +
DATENAME(YEAR, N.DATA_VENDA) FROM NOTAS_FISCAIS N INNER JOIN
ITENS_NOTAS_FISCAIS I ON N.NUMERO = I.NUMERO
INNER JOIN TABELA_DE_CLIENTES C ON N.CPF = C.CPF
WHERE YEAR(N.DATA_VENDA) = 2016
GROUP BY C.NOME, N.DATA_VENDA;