SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO IN
 (SELECT I.CODIGO_DO_PRODUTO FROM ITENS_NOTAS_FISCAIS I
INNER JOIN TABELA_DE_PRODUTOS P ON I.CODIGO_DO_PRODUTO = P.CODIGO_DO_PRODUTO
GROUP BY I.CODIGO_DO_PRODUTO, P.NOME_DO_PRODUTO HAVING SUM(I.QUANTIDADE) > 394000);